<?php
$_featureImgUrl = Mage::getBaseUrl();
$_bannerPath = Mage::getBaseUrl('media');
$bannerSlider = $this->getBannerSlider(2);
?>
<!--smartphone begin-->
<div class="smartphone">
    <!--div class="bx-title"><h2>smartphone</h2></div-->
    <div class="row" style="background: #fff;">
        <div class="col-md-3 col-sm-3 leftbox">
            <a href="#" style="display: block;max-height:590px;">
                <img class="img-responsive" src="<?php echo $_featureImgUrl.'\skin\frontend\tv_bigboom_package\tv_bigboom1\images\mivec\bl.jpg'?>" alt="">
            </a>
        </div>
        <div class="col-md-9 col-sm-9">
            <div style="border-color: #dfdfdf;border-style: solid;border-width: 1px;" class="clearfix">
                <div class="div-tabs f-left" style="width:80.6%;max-height:590px;">
                    <?php
                    if ($bannerSlider) :
                        $i = 1;
                        $_active = 'active';
                        foreach ($bannerSlider->getItems() as $slider) :
                            //print_r($slider);exit;
                            if ($i > 1) $_active = "";
                    ?>
                        <a class="<?php echo $_active?>" href="#">
                            <img src="<?php echo $_bannerPath."/" . $slider->getImage();?>" alt="br1">
                        </a>

                    <?php $i++;endforeach;endif;?>
                </div>
                <ul class="ul-tabs f-right" style="width:19.4%;height: 100%;">
                    <li class="active"><a href="javascript:void(0)"><img src="<?php echo $_featureImgUrl.'\skin\frontend\tv_bigboom_package\tv_bigboom1\images\mivec\one1.jpg'?>" alt="one"></a></li>
                    <li><a href="javascript:void(0)"><img src="<?php echo $_featureImgUrl.'\skin\frontend\tv_bigboom_package\tv_bigboom1\images\mivec\two1.jpg'?>" alt="two"></a></li>
                    <li><a href="javascript:void(0)"><img src="<?php echo $_featureImgUrl.'\skin\frontend\tv_bigboom_package\tv_bigboom1\images\mivec\three1.jpg'?>" alt="three"></a></li>
                </ul>
            </div>
            <script type="text/javascript">
                jQuery(document).ready(function($){
                    $(".ul-tabs li").click(function(){
                        if(!$(this).hasClass("active")){
                            var tmpIndex = $(this).index();
                            $(this).addClass("active").siblings().removeClass("active")
                                .parent().parent().find(".div-tabs>a").eq(tmpIndex).addClass("active").siblings().removeClass("active");
                        }
                    });
                });
            </script>
        </div>
    </div>
</div>
<!--smartphone finish-->